# Generated by Django 5.1.6 on 2025-02-16 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0002_rename_pages_book_total_pages_bookpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover',
        ),
    ]
