# Generated by Django 5.1.6 on 2025-02-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0003_remove_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(default='default.pdf', upload_to='books/pdfs/'),
        ),
        migrations.AlterField(
            model_name='bookpage',
            name='page_number',
            field=models.PositiveIntegerField(),
        ),
    ]
