# Generated by Django 5.1.6 on 2025-02-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
